name: converter
description: converter format text

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  responsive_framework: ^0.2.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  flutter_bloc: ^8.0.1
  xml: ^6.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
  - assets/values/
  - assets/values-it/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Bold.otf
          weight: 700
        - asset: assets/fonts/Proxima-Nova-Regular.ttf
          weight: 400
